services:
  - type: web
    name: pack-and-verify-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: UNSTRUCTURED_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.4"
